// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IDestroySystem {
  function destroy(uint builderNumber, int32 x, int32 y) external;
}