// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IIncrementSystem {
  function incrementWood(uint builderNumber, int32 x, int32 y) external returns (uint32);
  function incrementStone(uint builderNumber, int32 x, int32 y) external returns (uint32);
}
